CREATE TABLE [dbo].[Todo]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Task] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(1000) NOT NULL,
	[AssignedTo] INTEGER NOT NULL,
	[IsCompleted] BIT NOT NULL
)
