name: build-website

on:
  workflow_call:

jobs:
  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache .NET packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/TodoApp.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TodoApp.sln

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Build publishable website
        run: |
          dotnet publish --configuration Release
        working-directory: ./TodoApi

      - name: Zip publishable website
        run: |
          zip -r publish.zip .
        working-directory: ./TodoApi/bin/Release/net8.0/publish

      - name: Upload website as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: ./TodoApi/bin/Release/net8.0/publish/publish.zip

  build-database:
    name: Build database
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build database project
        working-directory: ./TodoDatabase
        run: MSBuild.exe TodoDatabase.sqlproj -property:Configuration=Release

      - name: Upload database as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: database
          path: ./TodoDatabase/bin/Release/TodoDatabase.dacpac
