name: deploy-api-website

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Bicep files
        run: |
          az bicep build --file ./infrastructure/deploy/main.bicep

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs:
      - lint
      - build
    with:
      environmentType: Production
      resourceGroupName: todoapi-grp
      sqlServerAdministratorLogin: nenad
      existingSqlServerName: todoapiserver
      existingDatabaseName: TodoDb
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQLSERVERADMINISTRATORLOGINPASSWORD }}
      jwtKey: ${{ secrets.JWTKEY }}
