name: deploy-api-website-with-database
concurrency: api-website-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Build the application and database.
  build:
    uses: ./.github/workflows/build.yml
  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  # Deploy the application and database to the test environment.
  deploy-test:
    uses: ./.github/workflows/deploy.yml
    needs:
      - lint
      - build
    with:
      environmentType: Test
      resourceGroupName: rg_sb_southeastasia_89803_3_171243429928
      sqlServerAdministratorLogin: nenad
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_TEST }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQLSERVERADMINISTRATORLOGINPASSWORD}}
      jwtKey: ${{ secrets.JWTKEY }}

  # Deploy the application and database.
  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs:
      - lint
      - build
      - deploy-test
    with:
      environmentType: Production
      resourceGroupName: rg_sb_eastus_89803_1_171243429770
      sqlServerAdministratorLogin: nenad
    secrets:
      AZURE_CLIENT_ID: ${{  secrets.AZURE_CLIENT_ID_PRODUCTION }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQLSERVERADMINISTRATORLOGINPASSWORD}}
      jwtKey: ${{ secrets.JWTKEY }}
