name: deploy-api-website-with-database
concurrency: api-website-deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  # Build the application and database.
  build:
    uses: ./.github/workflows/build.yml
  # Lint the Bicep file.
  lint:
    uses: ./.github/workflows/lint.yml

  deploy-production:
    uses: ./.github/workflows/deploy.yml
    needs:
      - lint
      - build
    with:
      resourceGroupName: rg_sb_eastus_89803_1_171208637558
      sqlServerAdministratorLogin: nenad
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      sqlServerAdministratorLoginPassword: ${{ secrets.SQLSERVERADMINISTRATORLOGINPASSWORD}}
      jwtKey: ${{ secrets.JWTKEY }}
